// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR9Zvbz6DPF3RHXtJRrXfjIHEuhIyq6MM',
    appId: '1:977787660840:web:cdbd79a803d2c50d0a631d',
    messagingSenderId: '977787660840',
    projectId: 'smartirrigationapp-929b3',
    authDomain: 'smartirrigationapp-929b3.firebaseapp.com',
    storageBucket: 'smartirrigationapp-929b3.firebasestorage.app',
    measurementId: 'G-KPJDL98MSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABns1_APrwZvAqodbL8EtjFtT6slQdijI',
    appId: '1:977787660840:android:254ccea684e63e620a631d',
    messagingSenderId: '977787660840',
    projectId: 'smartirrigationapp-929b3',
    storageBucket: 'smartirrigationapp-929b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhI6BdtxJkVl_nikoytTGH-I65qvXuBzg',
    appId: '1:977787660840:ios:a7345fc8282851470a631d',
    messagingSenderId: '977787660840',
    projectId: 'smartirrigationapp-929b3',
    storageBucket: 'smartirrigationapp-929b3.firebasestorage.app',
    iosBundleId: 'com.example.smartirrigation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhI6BdtxJkVl_nikoytTGH-I65qvXuBzg',
    appId: '1:977787660840:ios:a7345fc8282851470a631d',
    messagingSenderId: '977787660840',
    projectId: 'smartirrigationapp-929b3',
    storageBucket: 'smartirrigationapp-929b3.firebasestorage.app',
    iosBundleId: 'com.example.smartirrigation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR9Zvbz6DPF3RHXtJRrXfjIHEuhIyq6MM',
    appId: '1:977787660840:web:12deafa1d809126e0a631d',
    messagingSenderId: '977787660840',
    projectId: 'smartirrigationapp-929b3',
    authDomain: 'smartirrigationapp-929b3.firebaseapp.com',
    storageBucket: 'smartirrigationapp-929b3.firebasestorage.app',
    measurementId: 'G-2MK2FKM9T4',
  );
}
